std = "lua51"
unused_args = false
unused_secondaries = false
allow_defined_top = true
max_line_length = false
ignore = {
   "611",
   "612",
   "614",
}
exclude_files = {
   "Data/**",
   "Libs/**",
}

files["**/*.lua"] = {
   globals = {
      "MedaAuras",
      "MedaAurasDB",
      "MedaAurasCharDB",
      "MedaAuras_CreatureVO",
      "SLASH_MEDAAURAS1",
      "SLASH_MEDAAURAS2",
      "SLASH_MEDAREMINDERS1",
      _G = {other_fields = true},
      SlashCmdList = {read_only = false, other_fields = true},
      StaticPopupDialogs = {read_only = false, other_fields = true},
      C_Timer = {
         other_fields = true,
         fields = {
            After = {read_only = false},
            NewTimer = {read_only = false},
            NewTicker = {read_only = false},
         },
      },
   },

   read_globals = {
      "_G",
      "ADDON_LOADED",
      "AuraUtil",
      "BackdropTemplate",
      "BasicScriptErrors",
      "BugGrabber",
      "C_AddOns",
      "C_ChallengeMode",
      "C_ChatInfo",
      "C_PvP",
      "C_RestrictedActions",
      "C_Secrets",
      "C_Spell",
      "C_Timer",
      "C_UnitAuras",
      "CopyTable",
      "CreateFrame",
      "CreateFromMixins",
      "EnumerateFrames",
      "GameFontNormal",
      "GameFontNormalLarge",
      "GameFontNormalSmall",
      "GameTooltip",
      "GetInspectSpecialization",
      "GetAddOnMemoryUsage",
      "GetBuildInfo",
      "GetSubZoneText",
      "GetCursorPosition",
      "GetFramerate",
      "GetInstanceInfo",
      "GetObjectType",
      "GetNetStats",
      "GetNumGroupMembers",
      "GetScreenHeight",
      "GetScreenWidth",
      "GetSpecialization",
      "GetSpecializationInfo",
      "GetTime",
      "GetWorldElapsedTime",
      "InCombatLockdown",
      "CanInspect",
      "C_GossipInfo",
      "CombatLogGetCurrentEventInfo",
      "CreateColor",
      "IsInGroup",
      "IsEncounterInProgress",
      "IsInInstance",
      "IsInRaid",
      "IsPlayerSpell",
      "LibStub",
      "MapCanvasDataProviderMixin",
      "Minimap",
      "MuteSoundFile",
      "NotifyInspect",
      "PlaySound",
      "PlaySoundFile",
      "ReloadUI",
      "ResetCursor",
      "RunRecorder",
      "ScriptErrorsFrame",
      "SetCursor",
      "SlashCmdList",
      "StaticPopupDialogs",
      "StaticPopup_Hide",
      "StaticPopup_Show",
      "UIParent",
      "UISpecialFrames",
      "UpdateAddOnMemoryUsage",
      "UnitBuff",
      "UnitClass",
      "UnitExists",
      "UnitGUID",
      "UnitIsConnected",
      "UnitIsUnit",
      "UnitName",
      "UnmuteSoundFile",
      "WorldMapFrame",
      "WorldFrame",
      "canaccessvalue",
      "canaccesstable",
      "ChatFrame_AddMessageEventFilter",
      "ChatFrame_RemoveMessageEventFilter",
      "collectgarbage",
      "date",
      "debugstack",
      "format",
      "geterrorhandler",
      "hasanysecretvalues",
      "hooksecurefunc",
      "issecretvalue",
      "issecrettable",
      "loadstring",
      "print",
      "seterrorhandler",
      "strsplit",
      "strupper",
      "TalkingHeadFrame",
      "time",
      "tinsert",
      "tremove",
      "wipe",
   },
}
